name: medical-object-detection
channels:
      - conda-forge
      - defaults
dependencies:
      - python=3.7
      - tensorflow=2.0
      - numpy
      - jupyter
      - matplotlib
      - openslide
      - pillow
      - pyyaml
      - scikit-image